FurmularioDonaciones/Controllers/FormularioDonacionController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using FurmularioDonaciones.Models;
using FurmularioDonaciones.ViewModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace FurmularioDonaciones.Controllers
{
    public class FormularioDonacionController : Controller
    {
        private DB_A49FE7_BaseDonacionesContext _context;
        // GET: Formulario_Donacion_/Details/5
        public ActionResult ConsultaFormularioDonacion()

        {
            var formulario = _context.FormularioDonacion.FirstOrDefault();
            return View(formulario);
        }


        // GET: FormularioDonacionCreate/5
        public ActionResult FormularioDonacionCreate()
        {
            //foreach (var objetoModelSelectTemporal in listaMarcas)
            //{
            //    ModelSelect objetoSelect = new ModelSelect();
            //    objetoSelect.value = objetoModelSelectTemporal.IdMarca;
            //    objetoSelect.text = objetoModelSelectTemporal.NombreMarca;

            //    listaSelects.Add(objetoSelect);
            //}
            cargarMarcasSelect();
            return View();

        }


        [HttpPost]

        public ActionResult FormularioDonacionCreate(FormularioDonacion objetoFormularioDonacion, IFormFile Foto)
        {
            //recuperar un objeto de una variable de sesion, convirtiendo Json 
            var objetoUsuarioSesion = HttpContext.Session.GetString("UsuarioSesion");
            var objetoUsuarioFinal = JsonConvert.DeserializeObject<Usuario>(objetoUsuarioSesion);
            
            objetoFormularioDonacion.FechaAcopioDonacion = DateTime.Now;
            objetoFormularioDonacion.IdUsuario = objetoUsuarioFinal.IdUsuario;

            //objetoFormularioDonacion.IdMarca = 1;
            /* combertir una imagen en bits*/
            try
            {

                objetoFormularioDonacion.Tipoimagen = Foto.ContentType;

                var memoryStream = new MemoryStream();
                Foto.CopyTo(memoryStream);
                objetoFormularioDonacion.Foto = memoryStream.ToArray();


            }
            catch
            {
                Console.Write("No funca lguardar la foto  ");
            }


            bool bandera = GuardarFormulario(objetoFormularioDonacion);
            if (bandera == true)
            {
                TempData["MensajeIngreso"] = "Guardado";
                ModelState.Clear();
            }
            cargarMarcasSelect();
            return View();

         

        }


        // Contexto DB
        public FormularioDonacionController(DB_A49FE7_BaseDonacionesContext context)
        {
            _context = context;
        }


        // Cargar Marcas Select
        public void cargarMarcasSelect()
        {
            IEnumerable<Marcas> listaMarcas = _context.Marcas;

            List<ModelSelect> listaSelects = new List<ModelSelect>();

            var listaFinalSelects = listaMarcas.Select(x => new ModelSelect
            {
                value = x.IdMarca,
                text = x.NombreMarca
            }).ToList();
            ViewBag.ListaMarcasVista = listaFinalSelects;
        }
        // Funcion conbertir imagenes a bit

        //Funcion guardar nuevo Formulario de donaciones 
        public bool GuardarFormulario(FormularioDonacion objetoFormularioDonacion)
        {

            try
            {
                _context.FormularioDonacion.Add(objetoFormularioDonacion);
                _context.SaveChanges();

                return true;
            }
            catch (Exception exx)
            {
                return false;

            }

        }
    }
}

FurmularioDonaciones/Controllers/MarcaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FurmularioDonaciones.Models;
using Microsoft.AspNetCore.Mvc;

namespace FurmularioDonaciones.Controllers
{
    public class MarcaController : Controller
    {
        private DB_A49FE7_BaseDonacionesContext _context;

        //GET: Crear Marca
        public IActionResult CrearMarca()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CrearMarca(Marcas objetoMarca)
        {       

            bool bandera = GuardarMarca(objetoMarca);
            if(bandera == true)
            {
                TempData["MensajeIngreso"] = "Marca guardada";
                ModelState.Clear();
            }
            return View();
        }

        public MarcaController(DB_A49FE7_BaseDonacionesContext context)
        {
            _context = context;
        }

        public bool GuardarMarca(Marcas objetoMarca)
        {

            try
            {
                _context.Marcas.Add(objetoMarca);
                _context.SaveChanges();

                return true;
            }
            catch (Exception exx)
            {
                return false;

            }

        }
    }
}

FurmularioDonaciones/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using FurmularioDonaciones.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

using FurmularioDonaciones.ViewModel;
using System.Security.Cryptography;
using System.Text;

namespace FurmularioDonaciones.Controllers
{
    public class UsuarioController : Controller
    {
        private DB_A49FE7_BaseDonacionesContext _context;

        //GET: Crear Usuario
        public IActionResult CrearUsuario()

        {
            cargarRolesSelect();
            return View();
        }

        [HttpPost]
        public IActionResult CrearUsuario(Usuario objetoUsuario)

        {
            

            objetoUsuario.PasswordUsuario =  encriptarContrasena(objetoUsuario.PasswordUsuario); 




            bool bandera = GuardarUsuario(objetoUsuario);
            if (bandera)
            {
                TempData["MensajeExitoso"]="Usuario Guardado Correctamente.";
                ModelState.Clear();
            }
            else
            {
                TempData["MensajeFallido"] = "Error, el usuario no fue guardado.";

            }
            cargarRolesSelect();
            return View();
        }




        
        // Contexto DB
        public UsuarioController(DB_A49FE7_BaseDonacionesContext context)
        {
            _context = context;
        }



        // Funcion Cargar Roles Select
        public void cargarRolesSelect()
        {

            IEnumerable<Rol> listaRoles = _context.Rol;
            List<ModelSelect> listaSelect = new List<ModelSelect>();

            var listaFinalSelect = listaRoles.Select(x => new ModelSelect
            {
                value = x.IdRol,
                text = x.NombreRol

            });
            ViewBag.ListaRolesVista = listaFinalSelect;
        }
        public static string encriptarContrasena(string contrasena)
        {
            SHA256Managed encritado = new SHA256Managed();
            string encriptado1 = String.Empty;
            //Se cencripta la primera parte del codigo 
            byte[] crypto = encritado.ComputeHash(Encoding.ASCII.GetBytes(contrasena), 0, Encoding.ASCII.GetByteCount(contrasena));
            foreach (byte theByte in crypto)
            {
                encriptado1 += theByte.ToString("x2");
            }

            //Se ve necesario encriptar dos veces con diferente multiplicador
            string encriptado2 = "";
            foreach (byte theByte in crypto)
            {
                encriptado2 += theByte.ToString("x4");
            }

            string contrasenaEncriptada = encriptado1.ToString() + encriptado2.ToString();

            //Se regresa las dos cadenas y se corda 10 caracteres para aumentar la complejidad.
            return contrasenaEncriptada.Substring(0, contrasenaEncriptada.Length - 10);
        }//encriptarContrasena


        // Funcion Guardar Nuevo Usuario

        public bool GuardarUsuario(Usuario objetoUsuario)
        {

            try
            {
                _context.Usuario.Add(objetoUsuario);
                _context.SaveChanges();

                return true;
            }
            catch (Exception exx)
            {
                return false;

            }

        }
    }
}

FurmularioDonaciones/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Furmulario Donaciones</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/bootstrap/dist/css/bootstrap-datepicker.css" rel="stylesheet" />


    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="FormularioDonacion" asp-action="FormularioDonacionCreate">Furmulario Donaciones</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FormularioDonacion" asp-action="FormularioDonacionCreate">Crear Formulario</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="CrearUsuario">Crear Usuario</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Marca" asp-action="CrearMarca">Gestionar Marcas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Consultas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Furmulario Donaciones - Todos los derechos reservaedos a Jefferson Bárcenas
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap-datepicker.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>